blob/urls.py
from django.urls import path
from . import views

app_name='blob'
urlpatterns = [
    path('',views.index),
    path('articles/<int:article_id>/',views.articel_page,name="article_page"),
    path('edit/<int:article_id>/',views.edit_page,name="edit_page"),
    path('edit/action/',views.edit_action,name="edit_action"),
]

myblob/urls.py
from django.contrib import admin
from django.urls import path,include
import blob.views as bv

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blob/', include('blob.urls',namespace="blob")),
]

blob/models.py
from django.db import models

# Create your models here.
class Articel(models.Model):
    title=models.CharField(max_length=32,default="我是标题")
    content=models.TextField(null=True)
    pub_time=models.DateTimeField(null=True)

    def __str__(self):
        return self.title

blob/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models
# Create your views here.
def index(request):
    articles=models.Articel.objects.all()
    return render(request,"blob/index.html",{"articles":articles})

def articel_page(request,article_id):
    article=models.Articel.objects.get(pk=article_id)
    return render(request,"blob/article_page.html",{"article":article})

def edit_page(request,article_id):
    if str(article_id) == '0':
        return render(request,"blob/edit_page.html")
    else:
        article=models.Articel.objects.get(pk=article_id)
        return render(request,"blob/edit_page.html",{"article":article})

def edit_action(request):
    title=request.POST.get("title","TITLE")
    content=request.POST.get("content","CONTENT")
    article_id=request.POST.get("article_id","0")
    if article_id == "0":
        models.Articel.objects.create(title=title,content=content)
        articles=models.Articel.objects.all()
        return render(request,"blob/index.html",{"articles":articles})
    else:
        article=models.Articel.objects.get(pk=article_id)
        article.title=title
        article.content=content
        article.save()
        return render(request,"blob/article_page.html",{"article":article})

blob/templates/blob/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {{article.title}}
    <br>
    <h1><a href={% url "blob:edit_page" article.id %}>修改文章</a></h1>
</body>
</html>

blob/templates/blob/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <!-- 使用if else -->
    <!-- <form action={% url "blob:edit_action" %} method="post">
        {% csrf_token %}
        {% if article %}
        <input type="hidden" name="article_id" value="{{article.id}}">
        <label>
            文章标题
            <input type="text" name="title" value="{{article.title}}">
        </label>
        <br>
        <label>
            文章内容
            <input type="text" name="content" value="{{article.content}}">
        </label>
        {% else %}
        <input type="hidden" name="article_id" value="0">
        <label>
                文章标题
                <input type="text" name="title">
            </label>
            <br>
            <label>
                文章内容
                <input type="text" name="content">
            </label>
            {% endif %}
            <input type="submit">
    </form> -->
    <!-- 使用过滤器 -->
    <form action={% url "blob:edit_action" %} method="post">
        {% csrf_token %}
        <input type="hidden" name="article_id" value="{{ article.id | default:"0" }}">
        <label>
            文章标题
            <input type="text" name="title" value="{{article.title}}">
        </label>
        <br>
        <label>
            文章内容
            <input type="text" name="content" value="{{article.content}}">
        </label>
        <input type="submit">
    </form>
</body>
</html>

blob/templates/blob/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1><a href={% url "blob:edit_page" 0 %}>新文章</a></h1>
    {% for article in articles %}
    <a href={% url "blob:article_page" article.id %}>{{article.title}}</a>
    <br>
    {% endfor %}
</body>
</html>